name: Deploy scripts
run-name: ${{github.actor}} is deploying scripts to remote
on:
  push:
    branches:
      - main
jobs:
  deploy-password-generator:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy `password-generator.py`
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EXPERIMENT_VM_IP}}
          username: ${{secrets.EXPERIMENT_VM_SSH_USERNAME}}
          password: ${{secrets.EXPERIMENT_VM_SSH_PASSWORD}}
          port: 22
          source: "password-generator.py"
          target: "/opt/scripts"